/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import paneles.CambiaPanel;

/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        System.out.println("ahuevo");
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.btnAdminUser.setSelected(true);
        
        new CambiaPanel(pnlPrincipal, new paneles.pnlHome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCTextField1 = new app.bolivia.swing.JCTextField();
        pnlCentro = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        PNuevo = new javax.swing.JPanel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        rSButtonMetro3 = new rsbuttom.RSButtonMetro();
        panelProductos = new javax.swing.JPanel();
        btnAdminProductos = new rsbuttom.RSButtonMetro();
        panelEmpresa = new javax.swing.JPanel();
        btnInfoEmpresa = new rsbuttom.RSButtonMetro();
        subpanelProductos = new javax.swing.JPanel();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        rSButtonMetro6 = new rsbuttom.RSButtonMetro();
        rSButtonMetro7 = new rsbuttom.RSButtonMetro();
        panelConfiguracion = new javax.swing.JPanel();
        btnConfiguracion = new rsbuttom.RSButtonMetro();
        panelCerrarSesion = new javax.swing.JPanel();
        btnCerrarSesion = new rsbuttom.RSButtonMetro();
        btnAdminUser = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard - RojeruSan");

        jCTextField1.setBackground(new java.awt.Color(38, 86, 186));
        jCTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCTextField1.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField1.setPlaceholder("SEARCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(jCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(557, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));

        rSButtonMetro1.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro1.setForeground(new java.awt.Color(128, 128, 131));
        rSButtonMetro1.setText("Registrar usuarios");
        rSButtonMetro1.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro1.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro1.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro1.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro1.setColorTextPressed(new java.awt.Color(128, 128, 131));

        rSButtonMetro2.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro2.setForeground(new java.awt.Color(128, 128, 131));
        rSButtonMetro2.setText("Listar usuarios");
        rSButtonMetro2.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro2.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro2.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro2.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro2.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro2.setColorTextPressed(new java.awt.Color(128, 128, 131));

        rSButtonMetro3.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro3.setForeground(new java.awt.Color(128, 128, 131));
        rSButtonMetro3.setText("Modificar usuarios");
        rSButtonMetro3.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro3.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro3.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro3.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro3.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro3.setColorTextPressed(new java.awt.Color(128, 128, 131));

        javax.swing.GroupLayout PNuevoLayout = new javax.swing.GroupLayout(PNuevo);
        PNuevo.setLayout(PNuevoLayout);
        PNuevoLayout.setHorizontalGroup(
            PNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNuevoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(PNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNuevoLayout.setVerticalGroup(
            PNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnAdminProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnAdminProductos.setForeground(new java.awt.Color(128, 128, 131));
        btnAdminProductos.setText("Administrar Productos");
        btnAdminProductos.setColorHover(new java.awt.Color(204, 204, 204));
        btnAdminProductos.setColorNormal(new java.awt.Color(204, 204, 204));
        btnAdminProductos.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAdminProductos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAdminProductos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAdminProductos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAdminProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminProductosMousePressed(evt);
            }
        });
        btnAdminProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdminProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAdminProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        btnInfoEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        btnInfoEmpresa.setForeground(new java.awt.Color(128, 128, 131));
        btnInfoEmpresa.setText("Información de la empresa");
        btnInfoEmpresa.setColorHover(new java.awt.Color(204, 204, 204));
        btnInfoEmpresa.setColorNormal(new java.awt.Color(204, 204, 204));
        btnInfoEmpresa.setColorPressed(new java.awt.Color(204, 204, 204));
        btnInfoEmpresa.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnInfoEmpresa.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnInfoEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInfoEmpresaMousePressed(evt);
            }
        });
        btnInfoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEmpresaLayout = new javax.swing.GroupLayout(panelEmpresa);
        panelEmpresa.setLayout(panelEmpresaLayout);
        panelEmpresaLayout.setHorizontalGroup(
            panelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInfoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        panelEmpresaLayout.setVerticalGroup(
            panelEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInfoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        rSButtonMetro4.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setForeground(new java.awt.Color(128, 128, 131));
        rSButtonMetro4.setText("Registrar productos");
        rSButtonMetro4.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro4.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro4.setColorTextPressed(new java.awt.Color(128, 128, 131));

        rSButtonMetro5.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setForeground(new java.awt.Color(128, 128, 131));
        rSButtonMetro5.setText("Modificar productos");
        rSButtonMetro5.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro5.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro5.setColorTextPressed(new java.awt.Color(128, 128, 131));

        rSButtonMetro6.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setForeground(new java.awt.Color(128, 128, 131));
        rSButtonMetro6.setText("Listar productos");
        rSButtonMetro6.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro6.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro6.setColorTextPressed(new java.awt.Color(128, 128, 131));

        rSButtonMetro7.setBackground(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setForeground(new java.awt.Color(128, 128, 131));
        rSButtonMetro7.setText("Listar productos agotados");
        rSButtonMetro7.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setColorTextHover(new java.awt.Color(128, 128, 131));
        rSButtonMetro7.setColorTextNormal(new java.awt.Color(128, 128, 131));
        rSButtonMetro7.setColorTextPressed(new java.awt.Color(128, 128, 131));

        javax.swing.GroupLayout subpanelProductosLayout = new javax.swing.GroupLayout(subpanelProductos);
        subpanelProductos.setLayout(subpanelProductosLayout);
        subpanelProductosLayout.setHorizontalGroup(
            subpanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelProductosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(subpanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonMetro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subpanelProductosLayout.setVerticalGroup(
            subpanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanelProductosLayout.createSequentialGroup()
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        btnConfiguracion.setText("Configuración");
        btnConfiguracion.setColorHover(new java.awt.Color(204, 204, 204));
        btnConfiguracion.setColorNormal(new java.awt.Color(204, 204, 204));
        btnConfiguracion.setColorPressed(new java.awt.Color(204, 204, 204));
        btnConfiguracion.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnConfiguracion.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnConfiguracion.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConfiguracionMousePressed(evt);
            }
        });
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfiguracionLayout = new javax.swing.GroupLayout(panelConfiguracion);
        panelConfiguracion.setLayout(panelConfiguracionLayout);
        panelConfiguracionLayout.setHorizontalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        panelConfiguracionLayout.setVerticalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setForeground(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setColorHover(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setColorNormal(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setColorPressed(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMousePressed(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarSesionLayout = new javax.swing.GroupLayout(panelCerrarSesion);
        panelCerrarSesion.setLayout(panelCerrarSesionLayout);
        panelCerrarSesionLayout.setHorizontalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
        panelCerrarSesionLayout.setVerticalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        btnAdminUser.setBackground(new java.awt.Color(204, 204, 204));
        btnAdminUser.setForeground(new java.awt.Color(128, 128, 131));
        btnAdminUser.setText("Administrar Usuarios");
        btnAdminUser.setColorHover(new java.awt.Color(204, 204, 204));
        btnAdminUser.setColorNormal(new java.awt.Color(204, 204, 204));
        btnAdminUser.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAdminUser.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAdminUser.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAdminUser.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAdminUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminUserMousePressed(evt);
            }
        });
        btnAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subpanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAdminUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(btnAdminUser, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(PNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subpanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = pnlMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnInfoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoEmpresaActionPerformed
        if(this.btnInfoEmpresa.isSelected()){
            this.btnInfoEmpresa.setColorNormal(new Color(204,204,204));
            this.btnInfoEmpresa.setColorHover(new Color(204,204,204));
            this.btnInfoEmpresa.setColorPressed(new Color(204,204,204));

            this.btnAdminUser.setColorNormal(new Color(239,238,244));
            this.btnAdminUser.setColorHover(new Color(204,204,204));
            this.btnAdminUser.setColorPressed(new Color(204,204,204));
            
            this.btnAdminProductos.setColorNormal(new Color(239,238,244));
            this.btnAdminProductos.setColorHover(new Color(204,204,204));
            this.btnAdminProductos.setColorPressed(new Color(204,204,204));
            
            this.btnConfiguracion.setColorNormal(new Color(239,238,244));
            this.btnConfiguracion.setColorHover(new Color(204,204,204));
            this.btnConfiguracion.setColorPressed(new Color(204,204,204));
            
            this.btnCerrarSesion.setColorNormal(new Color(239,238,244));
            this.btnCerrarSesion.setColorHover(new Color(204,204,204));
            this.btnCerrarSesion.setColorPressed(new Color(204,204,204));
            
        }else{
            this.btnInfoEmpresa.setColorNormal(new Color(239,238,244));
            this.btnInfoEmpresa.setColorHover(new Color(204,204,204));
            this.btnInfoEmpresa.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnInfoEmpresaActionPerformed
    private void adminAction(){
       if(this.btnAdminProductos.isSelected()){
            this.btnAdminProductos.setColorNormal(new Color(204,204,204));
            this.btnAdminProductos.setColorHover(new Color(204,204,204));
            this.btnAdminProductos.setColorPressed(new Color(204,204,204));

            this.btnAdminUser.setColorNormal(new Color(239,238,244));
            this.btnAdminUser.setColorHover(new Color(204,204,204));
            this.btnAdminUser.setColorPressed(new Color(204,204,204));
            
            this.btnInfoEmpresa.setColorNormal(new Color(239,238,244));
            this.btnInfoEmpresa.setColorHover(new Color(204,204,204));
            this.btnInfoEmpresa.setColorPressed(new Color(204,204,204));
            
            this.btnConfiguracion.setColorNormal(new Color(239,238,244));
            this.btnConfiguracion.setColorHover(new Color(204,204,204));
            this.btnConfiguracion.setColorPressed(new Color(204,204,204));
            
            this.btnCerrarSesion.setColorNormal(new Color(239,238,244));
            this.btnCerrarSesion.setColorHover(new Color(204,204,204));
            this.btnCerrarSesion.setColorPressed(new Color(204,204,204));
            
        }else{
            this.btnAdminProductos.setColorNormal(new Color(239,238,244));
            this.btnAdminProductos.setColorHover(new Color(204,204,204));
            this.btnAdminProductos.setColorPressed(new Color(204,204,204));
        }
        if(panelEmpresa.getY()==194 || panelProductos.getY()!=96){
            if(panelProductos.getY()!=96){
               userAction();
           }
           Animacion.Animacion.bajar(424-panelConfiguracion.getHeight(), 424, 1, 2, panelConfiguracion);
           Animacion.Animacion.bajar(324-panelEmpresa.getHeight(),324, 1, 2, panelEmpresa);
           Animacion.Animacion.bajar(514-panelCerrarSesion.getHeight(), 514, 1, 2, panelCerrarSesion);
           
           Animacion.Animacion.subir( 174+subpanelProductos.getHeight(), 174,0, 10, subpanelProductos);
        }else{
            Animacion.Animacion.subir(304+panelConfiguracion.getHeight(), 304, 0, 2, panelConfiguracion);
            Animacion.Animacion.subir(194+panelEmpresa.getHeight(), 194, 0, 2, panelEmpresa);
            Animacion.Animacion.subir(404+panelCerrarSesion.getHeight(), 404, 0, 2, panelCerrarSesion);
            
            Animacion.Animacion.bajar(1224-subpanelProductos.getHeight(), 1224, 0, 10, subpanelProductos);
        } 
    }
    private void btnAdminProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminProductosActionPerformed
        adminAction();
    }//GEN-LAST:event_btnAdminProductosActionPerformed
    private void userAction(){
        if(this.btnAdminUser.isSelected()){
            this.btnAdminUser.setColorNormal(new Color(204,204,204));
            this.btnAdminUser.setColorHover(new Color(204,204,204));
            this.btnAdminUser.setColorPressed(new Color(204,204,204));

            this.btnAdminProductos.setColorNormal(new Color(239,238,244));
            this.btnAdminProductos.setColorHover(new Color(204,204,204));
            this.btnAdminProductos.setColorPressed(new Color(204,204,204));
            
            this.btnInfoEmpresa.setColorNormal(new Color(239,238,244));
            this.btnInfoEmpresa.setColorHover(new Color(204,204,204));
            this.btnInfoEmpresa.setColorPressed(new Color(204,204,204));
            
            this.btnConfiguracion.setColorNormal(new Color(239,238,244));
            this.btnConfiguracion.setColorHover(new Color(204,204,204));
            this.btnConfiguracion.setColorPressed(new Color(204,204,204));
            
            this.btnCerrarSesion.setColorNormal(new Color(239,238,244));
            this.btnCerrarSesion.setColorHover(new Color(204,204,204));
            this.btnCerrarSesion.setColorPressed(new Color(204,204,204));
        }else{
            this.btnAdminUser.setColorNormal(new Color(239,238,244));
            this.btnAdminUser.setColorHover(new Color(204,204,204));
            this.btnAdminUser.setColorPressed(new Color(204,204,204));
        }
        if(panelProductos.getY()==96){
           if(panelEmpresa.getY()!=194){
               adminAction();
           }
           Animacion.Animacion.bajar(194-panelProductos.getHeight(), 194, 1, 2, panelProductos);
           Animacion.Animacion.bajar(424-panelConfiguracion.getHeight(), 424, 1, 2, panelConfiguracion);
           Animacion.Animacion.bajar(324-panelEmpresa.getHeight(),324, 1, 2, panelEmpresa);
           Animacion.Animacion.bajar(514-panelCerrarSesion.getHeight(), 514, 1, 2, panelCerrarSesion);
           Animacion.Animacion.subir( 100+PNuevo.getHeight(), 100,0, 10, PNuevo);
        }else{
           Animacion.Animacion.subir(96+panelProductos.getHeight(), 96, 0, 2, panelProductos);
           Animacion.Animacion.subir(304+panelConfiguracion.getHeight(), 304, 0, 2, panelConfiguracion);
           Animacion.Animacion.subir(194+panelEmpresa.getHeight(), 194, 0, 2, panelEmpresa);
           Animacion.Animacion.subir(404+panelCerrarSesion.getHeight(), 404, 0, 2, panelCerrarSesion);
           Animacion.Animacion.bajar(980-PNuevo.getHeight(), 980, 0, 10, PNuevo);
        }
    }
    private void btnAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUserActionPerformed
        userAction();
    }//GEN-LAST:event_btnAdminUserActionPerformed

    private void btnAdminUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminUserMousePressed
        this.btnAdminUser.setSelected(true);
        this.btnAdminProductos.setSelected(false);
        this.btnInfoEmpresa.setSelected(false);
        this.btnConfiguracion.setSelected(false);
        this.btnCerrarSesion.setSelected(false);
    }//GEN-LAST:event_btnAdminUserMousePressed

    private void btnAdminProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminProductosMousePressed
        this.btnAdminUser.setSelected(false);
        this.btnAdminProductos.setSelected(true);
        this.btnInfoEmpresa.setSelected(false);
        this.btnConfiguracion.setSelected(false);
        this.btnCerrarSesion.setSelected(false);
    }//GEN-LAST:event_btnAdminProductosMousePressed

    private void btnInfoEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoEmpresaMousePressed
        this.btnAdminUser.setSelected(false);
        this.btnAdminProductos.setSelected(false);
        this.btnInfoEmpresa.setSelected(true);
        this.btnConfiguracion.setSelected(false);
        this.btnCerrarSesion.setSelected(false);
    }//GEN-LAST:event_btnInfoEmpresaMousePressed

    private void btnConfiguracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMousePressed
        this.btnAdminUser.setSelected(false);
        this.btnAdminProductos.setSelected(false);
        this.btnInfoEmpresa.setSelected(false);
        this.btnConfiguracion.setSelected(true);
        this.btnCerrarSesion.setSelected(false);
    }//GEN-LAST:event_btnConfiguracionMousePressed

    private void btnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMousePressed
        this.btnAdminUser.setSelected(false);
        this.btnAdminProductos.setSelected(false);
        this.btnInfoEmpresa.setSelected(false);
        this.btnConfiguracion.setSelected(false);
        this.btnCerrarSesion.setSelected(true);
    }//GEN-LAST:event_btnCerrarSesionMousePressed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        if(this.btnConfiguracion.isSelected()){
            this.btnConfiguracion.setColorNormal(new Color(204,204,204));
            this.btnConfiguracion.setColorHover(new Color(204,204,204));
            this.btnConfiguracion.setColorPressed(new Color(204,204,204));

            this.btnAdminUser.setColorNormal(new Color(239,238,244));
            this.btnAdminUser.setColorHover(new Color(204,204,204));
            this.btnAdminUser.setColorPressed(new Color(204,204,204));
            
            this.btnAdminProductos.setColorNormal(new Color(239,238,244));
            this.btnAdminProductos.setColorHover(new Color(204,204,204));
            this.btnAdminProductos.setColorPressed(new Color(204,204,204));
            
            this.btnInfoEmpresa.setColorNormal(new Color(239,238,244));
            this.btnInfoEmpresa.setColorHover(new Color(204,204,204));
            this.btnInfoEmpresa.setColorPressed(new Color(204,204,204));
            
            this.btnCerrarSesion.setColorNormal(new Color(239,238,244));
            this.btnCerrarSesion.setColorHover(new Color(204,204,204));
            this.btnCerrarSesion.setColorPressed(new Color(204,204,204));
            
        }else{
            this.btnConfiguracion.setColorNormal(new Color(239,238,244));
            this.btnConfiguracion.setColorHover(new Color(204,204,204));
            this.btnConfiguracion.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        if(this.btnCerrarSesion.isSelected()){
            this.btnCerrarSesion.setColorNormal(new Color(204,204,204));
            this.btnCerrarSesion.setColorHover(new Color(204,204,204));
            this.btnCerrarSesion.setColorPressed(new Color(204,204,204));

            this.btnAdminUser.setColorNormal(new Color(239,238,244));
            this.btnAdminUser.setColorHover(new Color(204,204,204));
            this.btnAdminUser.setColorPressed(new Color(204,204,204));
            
            this.btnAdminProductos.setColorNormal(new Color(239,238,244));
            this.btnAdminProductos.setColorHover(new Color(204,204,204));
            this.btnAdminProductos.setColorPressed(new Color(204,204,204));
            
            this.btnInfoEmpresa.setColorNormal(new Color(239,238,244));
            this.btnInfoEmpresa.setColorHover(new Color(204,204,204));
            this.btnInfoEmpresa.setColorPressed(new Color(204,204,204));
            
            this.btnConfiguracion.setColorNormal(new Color(239,238,244));
            this.btnConfiguracion.setColorHover(new Color(204,204,204));
            this.btnConfiguracion.setColorPressed(new Color(204,204,204));
            
        }else{
            this.btnCerrarSesion.setColorNormal(new Color(239,238,244));
            this.btnCerrarSesion.setColorHover(new Color(204,204,204));
            this.btnCerrarSesion.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PNuevo;
    private rsbuttom.RSButtonMetro btnAdminProductos;
    private rsbuttom.RSButtonMetro btnAdminUser;
    private rsbuttom.RSButtonMetro btnCerrarSesion;
    private rsbuttom.RSButtonMetro btnConfiguracion;
    private rsbuttom.RSButtonMetro btnInfoEmpresa;
    private javax.swing.JButton jButton1;
    private app.bolivia.swing.JCTextField jCTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCerrarSesion;
    private javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelEmpresa;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro3;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private rsbuttom.RSButtonMetro rSButtonMetro6;
    private rsbuttom.RSButtonMetro rSButtonMetro7;
    private javax.swing.JPanel subpanelProductos;
    // End of variables declaration//GEN-END:variables
}
