
import Principal.Login;
import configuracion.CodigoColor;
import configuracion.Configuracion;
import java.awt.Dimension;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author juanj
 */
public class FormMainAdmi2 extends javax.swing.JFrame {

    /**
     * Creates new form FormMainAdmi2
     */
    public FormMainAdmi2() {
        initComponents();
        btnAdministrarUsuarios.setIcon(new Configuracion().setIconoBoton("/imagenes/juan/administracion.png", btnAdministrarUsuarios));
        btnAdministrarProductos.setIcon(new Configuracion().setIconoBoton("/imagenes/juan/gestion-de-productos.png", btnAdministrarProductos));   
        btnGestionarEmpresa.setIcon(new Configuracion().setIconoBoton("/imagenes/juan/gestion-del-cambio.png", btnGestionarEmpresa));   
        agregarEstilos();
    }
    public void agregarEstilos() {
        //configuracion ventana
        this.setMinimumSize(new Dimension(700, 500));
        Configuracion.styles(this);

        //configuracon menu
        //Configuracion.normal(this.menuUser, this.menuProduct, this.menuMain, this.menuSettings, this.menuCompany);
        //Configuracion.normal(this.opcAddUser, this.opcUpdateUser, this.opcListUser);
        //Configuracion.normal(this.opcAddProduct, this.opcUpdateProduct, this.opcListProduct, this.opcListProductOut);

        //Configuracion.background(CodigoColor.cFondoGris2, this.menuUser, this.menuProduct, this.menuMain,
          ////      this.menuSettings, this.menuCompany);
        //Configuracion.background(CodigoColor.cFondoGris2, this.opcAddUser, this.opcUpdateUser, this.opcListUser);
        //Configuracion.background(CodigoColor.cFondoGris2, this.opcAddProduct, this.opcUpdateProduct,
          //      this.opcListProduct, this.opcListProductOut);

        //configuracion del JPanel
        Configuracion.background(CodigoColor.cFondoGris, this.jPanel1);

        //configuracion botones
        //Configuracion.normal(this.btnClose);
        Configuracion.foreground(CodigoColor.cLetrasBtnBlanco, this.btnClose);
        Configuracion.background(CodigoColor.cFondoBtnAzul, this.btnClose);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnAdministrarUsuarios = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnAdministrarProductos = new javax.swing.JButton();
        btnGestionarEmpresa = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdministrarUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        btnAdministrarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdministrarUsuarios.setForeground(new java.awt.Color(128, 128, 131));
        btnAdministrarUsuarios.setText("Administrar Usuarios");

        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClose.setText("Cerrar Sesion");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnAdministrarProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnAdministrarProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdministrarProductos.setForeground(new java.awt.Color(128, 128, 131));
        btnAdministrarProductos.setText("Administrar Productos");

        btnGestionarEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        btnGestionarEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGestionarEmpresa.setForeground(new java.awt.Color(128, 128, 131));
        btnGestionarEmpresa.setText("Datos de la empresa");
        btnGestionarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAdministrarUsuarios)
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(btnAdministrarProductos)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionarEmpresa)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnGestionarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormMainAdmi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormMainAdmi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormMainAdmi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormMainAdmi2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMainAdmi2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarProductos;
    private javax.swing.JButton btnAdministrarUsuarios;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGestionarEmpresa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
