/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.admin;

import com.settings.Configuracion;
import com.settings.CodigoColor;

public class PanelHomeAdmin extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public PanelHomeAdmin() {
        initComponents();
        configuracion();
    }
    
    private void configuracion(){
        //panel
        Configuracion.background(CodigoColor.cFondoBlanco, this);
        
        //label
        Configuracion.foreground(CodigoColor.cLetrasAzul, this.jlHome);
        Configuracion.robotoBold24(jlHome);
        
        Configuracion.foreground(CodigoColor.cLetrasGris, this.jlTittle);
        Configuracion.robotoBold24(jlTittle);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlImg02 = new javax.swing.JLabel();
        jlHome = new javax.swing.JLabel();
        jlImg01 = new javax.swing.JLabel();
        jlTittle = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jlImg02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/admin/homeAdmin250.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        add(jlImg02, gridBagConstraints);

        jlHome.setText("Home Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        add(jlHome, gridBagConstraints);

        jlImg01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 0, 9);
        add(jlImg01, gridBagConstraints);

        jlTittle.setText("Bienvenido Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.insets = new java.awt.Insets(19, 19, 19, 19);
        add(jlTittle, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlHome;
    private javax.swing.JLabel jlImg01;
    private javax.swing.JLabel jlImg02;
    private javax.swing.JLabel jlTittle;
    // End of variables declaration//GEN-END:variables
}
