/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.admin;

import com.librery.Animacion;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.admin.CambiaPanel;
import com.main.Login;

/**
 *
 * @author RojeruSan
 */
public class PrincipalAdmin extends javax.swing.JFrame {

    int x, y;

    /**
     * Creates new form Principal
     */

    public PrincipalAdmin() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.btnAdminUser.setSelected(true);

        //Animacion.bajar(PNuevo.getY(), PNuevo.getY()+PNuevo.getHeight()*5, 1, 10, PNuevo);
        //Animacion.bajar(subpanelProductos.getY(), subpanelProductos.getY()+subpanelProductos.getHeight()*5, 1, 10, subpanelProductos);
        new CambiaPanel(pnlPrincipal, new PanelHomeAdmi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnAdminUser = new com.librery.RSButtonMetro();
        btnInfoEmpresa = new com.librery.RSButtonMetro();
        btnAdminProductos = new com.librery.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        btnConfiguracion = new com.librery.RSButtonMetro();
        btnCerrarSesion = new com.librery.RSButtonMetro();
        btnListarProductos = new com.librery.RSButtonMetro();
        btnListarUsuarios = new com.librery.RSButtonMetro();
        btnHome = new com.librery.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCTextField1 = new com.librery.JCTextField();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));

        btnAdminUser.setForeground(new java.awt.Color(128, 128, 131));
        btnAdminUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administracion.png"))); // NOI18N
        btnAdminUser.setText("Administrar Usuarios");
        btnAdminUser.setColorHover(new java.awt.Color(204, 204, 204));
        btnAdminUser.setColorNormal(new java.awt.Color(204, 204, 204));
        btnAdminUser.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAdminUser.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAdminUser.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAdminUser.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAdminUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminUser.setIconTextGap(25);
        btnAdminUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminUserMousePressed(evt);
            }
        });
        btnAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUserActionPerformed(evt);
            }
        });

        btnInfoEmpresa.setBackground(new java.awt.Color(239, 238, 244));
        btnInfoEmpresa.setForeground(new java.awt.Color(128, 128, 131));
        btnInfoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-del-cambio.png"))); // NOI18N
        btnInfoEmpresa.setText("Datos de la Empresa");
        btnInfoEmpresa.setColorHover(new java.awt.Color(204, 204, 204));
        btnInfoEmpresa.setColorNormal(new java.awt.Color(239, 238, 244));
        btnInfoEmpresa.setColorPressed(new java.awt.Color(204, 204, 204));
        btnInfoEmpresa.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnInfoEmpresa.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnInfoEmpresa.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnInfoEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInfoEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInfoEmpresa.setIconTextGap(19);
        btnInfoEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInfoEmpresaMousePressed(evt);
            }
        });
        btnInfoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoEmpresaActionPerformed(evt);
            }
        });

        btnAdminProductos.setBackground(new java.awt.Color(239, 238, 244));
        btnAdminProductos.setForeground(new java.awt.Color(128, 128, 131));
        btnAdminProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-de-productos.png"))); // NOI18N
        btnAdminProductos.setText("Administrar Productos");
        btnAdminProductos.setColorHover(new java.awt.Color(204, 204, 204));
        btnAdminProductos.setColorNormal(new java.awt.Color(239, 238, 244));
        btnAdminProductos.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAdminProductos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAdminProductos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAdminProductos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAdminProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminProductos.setIconTextGap(25);
        btnAdminProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminProductosMousePressed(evt);
            }
        });
        btnAdminProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminProductosActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(239, 238, 244));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        btnConfiguracion.setBackground(new java.awt.Color(239, 238, 244));
        btnConfiguracion.setForeground(new java.awt.Color(128, 128, 131));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuracion.png"))); // NOI18N
        btnConfiguracion.setText("Configuración");
        btnConfiguracion.setColorHover(new java.awt.Color(204, 204, 204));
        btnConfiguracion.setColorNormal(new java.awt.Color(239, 238, 244));
        btnConfiguracion.setColorPressed(new java.awt.Color(204, 204, 204));
        btnConfiguracion.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnConfiguracion.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnConfiguracion.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfiguracion.setIconTextGap(19);
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConfiguracionMousePressed(evt);
            }
        });
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(239, 238, 244));
        btnCerrarSesion.setForeground(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setColorHover(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setColorNormal(new java.awt.Color(239, 238, 244));
        btnCerrarSesion.setColorPressed(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCerrarSesion.setIconTextGap(19);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMousePressed(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnListarProductos.setBackground(new java.awt.Color(239, 238, 244));
        btnListarProductos.setForeground(new java.awt.Color(128, 128, 131));
        btnListarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-de-productos.png"))); // NOI18N
        btnListarProductos.setText("Listar Productos");
        btnListarProductos.setColorHover(new java.awt.Color(204, 204, 204));
        btnListarProductos.setColorNormal(new java.awt.Color(239, 238, 244));
        btnListarProductos.setColorPressed(new java.awt.Color(204, 204, 204));
        btnListarProductos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnListarProductos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnListarProductos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnListarProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListarProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnListarProductos.setIconTextGap(25);
        btnListarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListarProductosMousePressed(evt);
            }
        });
        btnListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductosActionPerformed(evt);
            }
        });

        btnListarUsuarios.setBackground(new java.awt.Color(239, 238, 244));
        btnListarUsuarios.setForeground(new java.awt.Color(128, 128, 131));
        btnListarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-de-productos.png"))); // NOI18N
        btnListarUsuarios.setText("Listar Usuarios");
        btnListarUsuarios.setColorHover(new java.awt.Color(204, 204, 204));
        btnListarUsuarios.setColorNormal(new java.awt.Color(239, 238, 244));
        btnListarUsuarios.setColorPressed(new java.awt.Color(204, 204, 204));
        btnListarUsuarios.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnListarUsuarios.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnListarUsuarios.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnListarUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnListarUsuarios.setIconTextGap(25);
        btnListarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListarUsuariosMousePressed(evt);
            }
        });
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });

        btnHome.setForeground(new java.awt.Color(128, 128, 131));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setColorHover(new java.awt.Color(204, 204, 204));
        btnHome.setColorNormal(new java.awt.Color(204, 204, 204));
        btnHome.setColorPressed(new java.awt.Color(204, 204, 204));
        btnHome.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnHome.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnHome.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setIconTextGap(25);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInfoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdminProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInfoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema Ventas");

        jCTextField1.setBackground(new java.awt.Color(38, 86, 186));
        jCTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCTextField1.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField1.setPlaceholder("SEARCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                .addComponent(jCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void userAction() {
        if (this.btnAdminUser.isSelected())
        {
            this.btnAdminUser.setColorNormal(new Color(204, 204, 204));
            this.btnAdminUser.setColorHover(new Color(204, 204, 204));
            this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

            this.btnAdminProductos.setColorNormal(new Color(239, 238, 244));
            this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
            this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));

            this.btnInfoEmpresa.setColorNormal(new Color(239, 238, 244));
            this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
            this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));

            this.btnConfiguracion.setColorNormal(new Color(239, 238, 244));
            this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
            this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));

            this.btnCerrarSesion.setColorNormal(new Color(239, 238, 244));
            this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
            this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));
        } else
        {
            this.btnAdminUser.setColorNormal(new Color(239, 238, 244));
            this.btnAdminUser.setColorHover(new Color(204, 204, 204));
            this.btnAdminUser.setColorPressed(new Color(204, 204, 204));
        }
        /*if(btnAdminProductos.getY()==96){
           if(btnInfoEmpresa.getY()!=194){
               adminAction();
           }
           Animacion.bajar(194-btnAdminProductos.getHeight(), 194, 1, 2, btnAdminProductos);
           Animacion.bajar(424-btnConfiguracion.getHeight(), 424, 1, 2, btnConfiguracion);
           Animacion.bajar(324-btnInfoEmpresa.getHeight(),324, 1, 2, btnInfoEmpresa);
           Animacion.bajar(514-btnCerrarSesion.getHeight(), 514, 1, 2, btnCerrarSesion);
           Animacion.subir( 100+PNuevo.getHeight(), 100,0, 10, PNuevo);
        }else{
           Animacion.subir(96+btnAdminProductos.getHeight(), 96, 0, 2, btnAdminProductos);
           Animacion.subir(304+btnConfiguracion.getHeight(), 304, 0, 2, btnConfiguracion);
           Animacion.subir(194+btnInfoEmpresa.getHeight(), 194, 0, 2, btnInfoEmpresa);
           Animacion.subir(404+btnCerrarSesion.getHeight(), 404, 0, 2, btnCerrarSesion);
           Animacion.bajar(980-PNuevo.getHeight(), 980, 0, 10, PNuevo);
        }*/
    }
    private void btnAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUserActionPerformed
        try
        {
            new CambiaPanel(pnlPrincipal, new com.admin.PanelUser());
            if (this.btnAdminUser.isSelected())
            {
                this.btnAdminUser.setColorNormal(new Color(204, 204, 204));
                this.btnAdminUser.setColorHover(new Color(204, 204, 204));
                this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

                this.btnAdminUser.setColorNormal(new Color(239, 238, 244));
                this.btnAdminUser.setColorHover(new Color(204, 204, 204));
                this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

                this.btnAdminProductos.setColorNormal(new Color(239, 238, 244));
                this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
                this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));

                this.btnConfiguracion.setColorNormal(new Color(239, 238, 244));
                this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
                this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));

                this.btnCerrarSesion.setColorNormal(new Color(239, 238, 244));
                this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
                this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));
            } else
            {
                this.btnInfoEmpresa.setColorNormal(new Color(239, 238, 244));
                this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));
            }
        } catch (Exception e)
        {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_btnAdminUserActionPerformed

    private void btnAdminUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminUserMousePressed
        try
        {
            this.btnAdminUser.setSelected(true);
            this.btnHome.setSelected(false);
            this.btnListarUsuarios.setSelected(false);
            this.btnListarProductos.setSelected(false);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnAdminUserMousePressed

    private void btnInfoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoEmpresaActionPerformed
        try
        {
            new CambiaPanel(pnlPrincipal, new com.admin.PanelProducto());
            if (this.btnInfoEmpresa.isSelected())
            {
                this.btnInfoEmpresa.setColorNormal(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));
            
                this.btnAdminUser.setColorNormal(new Color(239, 238, 244));
                this.btnAdminUser.setColorHover(new Color(204, 204, 204));
                this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

                this.btnAdminProductos.setColorNormal(new Color(239, 238, 244));
                this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
                this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));

                this.btnConfiguracion.setColorNormal(new Color(239, 238, 244));
                this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
                this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));

                this.btnCerrarSesion.setColorNormal(new Color(239, 238, 244));
                this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
                this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));
            } else
            {
                this.btnInfoEmpresa.setColorNormal(new Color(239, 238, 244));
                this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));
            }
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnInfoEmpresaActionPerformed

    private void btnInfoEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoEmpresaMousePressed
        try
        {
            this.btnHome.setSelected(false);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(false);
            this.btnListarProductos.setSelected(false);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(true);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnInfoEmpresaMousePressed

    private void btnAdminProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminProductosMousePressed
        try
        {
            this.btnHome.setSelected(false);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(false);
            this.btnListarProductos.setSelected(false);
            this.btnAdminProductos.setSelected(true);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnAdminProductosMousePressed
    private void adminAction() {
        if (this.btnAdminProductos.isSelected())
        {
            this.btnAdminProductos.setColorNormal(new Color(204, 204, 204));
            this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
            this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));

            this.btnAdminUser.setColorNormal(new Color(239, 238, 244));
            this.btnAdminUser.setColorHover(new Color(204, 204, 204));
            this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

            this.btnInfoEmpresa.setColorNormal(new Color(239, 238, 244));
            this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
            this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));

            this.btnConfiguracion.setColorNormal(new Color(239, 238, 244));
            this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
            this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));

            this.btnCerrarSesion.setColorNormal(new Color(239, 238, 244));
            this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
            this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));

        } else
        {
            this.btnAdminProductos.setColorNormal(new Color(239, 238, 244));
            this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
            this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));
        }
        /*if(btnInfoEmpresa.getY()==194 || btnAdminProductos.getY()!=96){
            if(btnAdminProductos.getY()!=96){
               userAction();
           }
           Animacion.bajar(424-btnConfiguracion.getHeight(), 424, 1, 2, btnConfiguracion);
           Animacion.bajar(324-btnInfoEmpresa.getHeight(),324, 1, 2, btnInfoEmpresa);
           Animacion.bajar(514-btnCerrarSesion.getHeight(), 514, 1, 2, btnCerrarSesion);
           
           Animacion.subir( 174+subpanelProductos.getHeight(), 174,0, 10, subpanelProductos);
        }else{
           Animacion.subir(304+btnConfiguracion.getHeight(), 304, 0, 2, btnConfiguracion);
           Animacion.subir(194+btnInfoEmpresa.getHeight(), 194, 0, 2, btnInfoEmpresa);
           Animacion.subir(404+btnCerrarSesion.getHeight(), 404, 0, 2, btnCerrarSesion);
            
           Animacion.bajar(1224-subpanelProductos.getHeight(), 1224, 0, 10, subpanelProductos);
        } */
    }
    private void btnAdminProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminProductosActionPerformed
        try
        {
            new CambiaPanel(pnlPrincipal, new com.admin.PanelProducto());
            if (this.btnInfoEmpresa.isSelected())
            {
                this.btnInfoEmpresa.setColorNormal(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));

                this.btnAdminUser.setColorNormal(new Color(239, 238, 244));
                this.btnAdminUser.setColorHover(new Color(204, 204, 204));
                this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

                this.btnAdminProductos.setColorNormal(new Color(239, 238, 244));
                this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
                this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));

                this.btnConfiguracion.setColorNormal(new Color(239, 238, 244));
                this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
                this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));

                this.btnCerrarSesion.setColorNormal(new Color(239, 238, 244));
                this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
                this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));
            } else
            {
                this.btnInfoEmpresa.setColorNormal(new Color(239, 238, 244));
                this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));
            }
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnAdminProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            int posicion = pnlMenu.getX();
            if (posicion > -1)
            {
                Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
            } else
            {
                Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
            }
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        try
        {
            if (this.btnCerrarSesion.isSelected())
            {
                this.btnAdminUser.setColorNormal(new Color(239, 238, 244));
                this.btnAdminUser.setColorHover(new Color(204, 204, 204));
                this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

                this.btnAdminProductos.setColorNormal(new Color(239, 238, 244));
                this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
                this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));

                this.btnInfoEmpresa.setColorNormal(new Color(239, 238, 244));
                this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));

                this.btnConfiguracion.setColorNormal(new Color(239, 238, 244));
                this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
                this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));

                this.btnCerrarSesion.setColorNormal(new Color(204, 204, 204));
                this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
                this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));

            } else
            {
                this.btnCerrarSesion.setColorNormal(new Color(239, 238, 244));
                this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
                this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));
            }
            this.dispose();
            Login log=new Login();
            log.setVisible(true);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMousePressed
        try
        {
            this.btnHome.setSelected(false);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(false);
            this.btnListarProductos.setSelected(false);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(true);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnCerrarSesionMousePressed

    private void btnConfiguracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMousePressed
        try
        {
            this.btnHome.setSelected(false);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(false);
            this.btnListarProductos.setSelected(false);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(true);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnConfiguracionMousePressed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        try
        {
            new CambiaPanel(pnlPrincipal, new com.admin.pnlFeeBack());
            if (this.btnConfiguracion.isSelected())
            {
                this.btnAdminUser.setColorNormal(new Color(239, 238, 244));
                this.btnAdminUser.setColorHover(new Color(204, 204, 204));
                this.btnAdminUser.setColorPressed(new Color(204, 204, 204));

                this.btnAdminProductos.setColorNormal(new Color(239, 238, 244));
                this.btnAdminProductos.setColorHover(new Color(204, 204, 204));
                this.btnAdminProductos.setColorPressed(new Color(204, 204, 204));

                this.btnInfoEmpresa.setColorNormal(new Color(239, 238, 244));
                this.btnInfoEmpresa.setColorHover(new Color(204, 204, 204));
                this.btnInfoEmpresa.setColorPressed(new Color(204, 204, 204));

                this.btnConfiguracion.setColorNormal(new Color(204, 204, 204));
                this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
                this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));

                this.btnCerrarSesion.setColorNormal(new Color(239, 238, 244));
                this.btnCerrarSesion.setColorHover(new Color(204, 204, 204));
                this.btnCerrarSesion.setColorPressed(new Color(204, 204, 204));
            } else
            {
                this.btnConfiguracion.setColorNormal(new Color(239, 238, 244));
                this.btnConfiguracion.setColorHover(new Color(204, 204, 204));
                this.btnConfiguracion.setColorPressed(new Color(204, 204, 204));
            }
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnListarProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarProductosMousePressed
        try
        {
            this.btnHome.setSelected(false);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(false);
            this.btnListarProductos.setSelected(true);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnListarProductosMousePressed

    private void btnListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductosActionPerformed
        try
        {
            
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnListarProductosActionPerformed

    private void btnListarUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarUsuariosMousePressed
        try
        {
            this.btnHome.setSelected(false);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(true);
            this.btnListarProductos.setSelected(false);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnListarUsuariosMousePressed

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed
        try
        {
            this.btnHome.setSelected(false);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(true);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        try
        {
            this.btnHome.setSelected(true);
            this.btnAdminUser.setSelected(false);
            this.btnListarUsuarios.setSelected(false);
            this.btnListarProductos.setSelected(false);
            this.btnAdminProductos.setSelected(false);
            this.btnInfoEmpresa.setSelected(false);
            this.btnConfiguracion.setSelected(false);
            this.btnCerrarSesion.setSelected(false);
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        try
        {
            new CambiaPanel(pnlPrincipal, new PanelHomeAdmi());
        } catch (Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new PrincipalAdmin().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
                {
                    Logger.getLogger(PrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.librery.RSButtonMetro btnAdminProductos;
    private com.librery.RSButtonMetro btnAdminUser;
    private com.librery.RSButtonMetro btnCerrarSesion;
    private com.librery.RSButtonMetro btnConfiguracion;
    private com.librery.RSButtonMetro btnHome;
    private com.librery.RSButtonMetro btnInfoEmpresa;
    private com.librery.RSButtonMetro btnListarProductos;
    private com.librery.RSButtonMetro btnListarUsuarios;
    private javax.swing.JButton jButton1;
    private com.librery.JCTextField jCTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
