/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ventas.administrador;

import Objetos.Producto;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author corte
 */
public class Agregar_Producto extends javax.swing.JDialog {
    Producto producto;
    /**
     * Creates new form Agregrar_Producto
     */
    public Agregar_Producto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelagregarproducto = new javax.swing.JLabel();
        labelnombre = new javax.swing.JLabel();
        labelcodigo = new javax.swing.JLabel();
        labelprecio = new javax.swing.JLabel();
        labelarea = new javax.swing.JLabel();
        labelmarca = new javax.swing.JLabel();
        labelcantidad = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        tfcodigo = new javax.swing.JTextField();
        tfprecio = new javax.swing.JTextField();
        tfarea = new javax.swing.JTextField();
        tfmarca = new javax.swing.JTextField();
        tfcantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelagregarproducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelagregarproducto.setForeground(new java.awt.Color(0, 51, 204));
        labelagregarproducto.setText("Agregar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 12, 0, 0);
        getContentPane().add(labelagregarproducto, gridBagConstraints);

        labelnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelnombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 49, 0, 0);
        getContentPane().add(labelnombre, gridBagConstraints);

        labelcodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcodigo.setText("Codigo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 56, 0, 0);
        getContentPane().add(labelcodigo, gridBagConstraints);

        labelprecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelprecio.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 49, 0, 0);
        getContentPane().add(labelprecio, gridBagConstraints);

        labelarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelarea.setText("Area:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 49, 0, 0);
        getContentPane().add(labelarea, gridBagConstraints);

        labelmarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelmarca.setText("Marca:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 49, 0, 0);
        getContentPane().add(labelmarca, gridBagConstraints);

        labelcantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcantidad.setText("Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 49, 0, 0);
        getContentPane().add(labelcantidad, gridBagConstraints);

        tfnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfnombreKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 12, 0, 0);
        getContentPane().add(tfnombre, gridBagConstraints);

        tfcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcodigoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 12, 0, 0);
        getContentPane().add(tfcodigo, gridBagConstraints);

        tfprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfprecioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 12, 0, 0);
        getContentPane().add(tfprecio, gridBagConstraints);

        tfarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfareaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 12, 0, 0);
        getContentPane().add(tfarea, gridBagConstraints);

        tfmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfmarcaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 12, 0, 0);
        getContentPane().add(tfmarca, gridBagConstraints);

        tfcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcantidadKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 18, 0, 0);
        getContentPane().add(tfcantidad, gridBagConstraints);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        btnRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnRegistrarKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 164, 18, 36);
        getContentPane().add(btnRegistrar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try
        {
            if(!tfcodigo.getText().isEmpty() && !tfnombre.getText().isEmpty() && !tfprecio.getText().isEmpty() && !tfarea.getText().isEmpty() && !tfmarca.getText().isEmpty() && !tfcantidad.getText().isEmpty()){
                producto=new Producto(Long.parseLong(tfcodigo.getText()), tfnombre.getText(), Double.parseDouble(tfprecio.getText()), tfarea.getText(), tfmarca.getText(), Double.parseDouble(tfcantidad.getText()));
            }else{
                JOptionPane.showMessageDialog(null, "Verifica los datos ingresados!");
            }
            dispose();
        } catch (Exception e)
        {
            System.err.print(e);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistrarKeyTyped
    

    }//GEN-LAST:event_btnRegistrarKeyTyped

    private void tfcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcodigoKeyTyped
        try
        {
            char cTeclaPresionada=evt.getKeyChar();
            if(cTeclaPresionada==KeyEvent.VK_ENTER){
                btnRegistrar.doClick();
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_tfcodigoKeyTyped

    private void tfnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnombreKeyTyped
        try
        {
            char cTeclaPresionada=evt.getKeyChar();
            if(cTeclaPresionada==KeyEvent.VK_ENTER){
                btnRegistrar.doClick();
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_tfnombreKeyTyped

    private void tfprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfprecioKeyTyped
        try
        {
            char cTeclaPresionada=evt.getKeyChar();
            if(cTeclaPresionada==KeyEvent.VK_ENTER){
                btnRegistrar.doClick();
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_tfprecioKeyTyped

    private void tfareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfareaKeyTyped
        try
        {
            char cTeclaPresionada=evt.getKeyChar();
            if(cTeclaPresionada==KeyEvent.VK_ENTER){
                btnRegistrar.doClick();
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_tfareaKeyTyped

    private void tfmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmarcaKeyTyped
        try
        {
            char cTeclaPresionada=evt.getKeyChar();
            if(cTeclaPresionada==KeyEvent.VK_ENTER){
                btnRegistrar.doClick();
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_tfmarcaKeyTyped

    private void tfcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcantidadKeyTyped
        try
        {
            char cTeclaPresionada=evt.getKeyChar();
            if(cTeclaPresionada==KeyEvent.VK_ENTER){
                btnRegistrar.doClick();
            }
        } catch (Exception e)
        {
        }
    }//GEN-LAST:event_tfcantidadKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agregar_Producto dialog = new Agregar_Producto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public Producto getProducto(){
        return this.producto;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel labelagregarproducto;
    private javax.swing.JLabel labelarea;
    private javax.swing.JLabel labelcantidad;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labelmarca;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labelprecio;
    private javax.swing.JTextField tfarea;
    private javax.swing.JTextField tfcantidad;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfmarca;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField tfprecio;
    // End of variables declaration//GEN-END:variables
}
