/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.table;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author juanj
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
        ImageIcon wallpaperDelete = new ImageIcon("src/main/resources/images/icono/delete.png");
        //Icon iconoDelete = new ImageIcon(wallpaperDelete.getImage().getScaledInstance(delete.getWidth(), delete.getHeight(), Image.SCALE_DEFAULT)); 
        
        ImageIcon wallpaperEdit = new ImageIcon("src/main/resources/images/icono/edit.png");
        //Icon iconoEdit = new ImageIcon(wallpaperEdit.getImage().getScaledInstance(edit.getWidth(), edit.getHeight(), Image.SCALE_DEFAULT)); 
        
        ImageIcon wallpaperView = new ImageIcon("src/main/resources/images/icono/view.png");
        //Icon iconoView = new ImageIcon(wallpaperView.getImage().getScaledInstance(view.getWidth(), view.getHeight(), Image.SCALE_DEFAULT)); 
        
        //this.delete.setIcon(new ImageIcon(wallpaperDelete.getImage().getScaledInstance(delete.getWidth(), delete.getHeight(), Image.SCALE_DEFAULT)));
        //this.edit.setIcon(new ImageIcon(wallpaperEdit.getImage().getScaledInstance(edit.getWidth(), edit.getHeight(), Image.SCALE_DEFAULT)));
        //this.view.setIcon(new ImageIcon(wallpaperView.getImage().getScaledInstance(view.getWidth(), view.getHeight(), Image.SCALE_DEFAULT))); 
        //this.repaint(); 
    }
    public void initEvent(TableActionEvent event,int row){
        edit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onEdit(row);
            }
        });
        delete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onDelete(row);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit = new com.table.ActionButton();
        delete = new com.table.ActionButton();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.table.ActionButton delete;
    private com.table.ActionButton edit;
    // End of variables declaration//GEN-END:variables
}
